--- 
:gogrid: 
  :username: API key
  :password: GoGrid Account password
  :name: Gogrid
:mock: 
  :username: Username
  :password: Password
  :name: Mock
:rhevm: 
  :username: RHEV-M Username (with domain)
  :password: RHEV-M Password
  :name: RHEVM
:rimuhosting: 
  :username: API key
  :password: API password
  :name: RimuHosting
:opennebula: 
  :class: OpennebulaDriver
  :name: Opennebula
:sbc: 
  :name: SBC
:terremark: 
  :name: Terremark
:rackspace: 
  :username: API key
  :password: Rackspace password
  :name: Rackspace
:azure: 
  :name: Azure
:ec2: 
  :entrypoints: 
    s3: 
      us-west-1: s3-us-west-1.amazonaws.com
      ap-southeast-1: s3-ap-southeast-1.amazonaws.com
      eu-west-1: s3-eu-west-1.amazonaws.com
      us-east-1: s3.amazonaws.com
    elb: 
      us-west-1: elasticloadbalancing.us-west-1.amazonaws.com
      ap-southeast-1: elasticloadbalancing.ap-southeast-1.amazonaws.com
      eu-west-1: elasticloadbalancing.eu-west-1.amazonaws.com
      us-east-1: elasticloadbalancing.us-east-1.amazonaws.com
    ec2: 
      us-west-1: ec2.us-west-1.amazonaws.com
      ap-southeast-1: ec2.ap-southeast-1.amazonaws.com
      eu-west-1: ec2.eu-west-1.amazonaws.com
      us-east-1: ec2.us-east-1.amazonaws.com
  :username: Access Key ID
  :password: Secret Access Key
  :name: EC2
